import java.awt.*;
import java.util.ArrayList;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author t00618738
 */
public class Application extends javax.swing.JFrame {

ArrayList<Photo> photos = new ArrayList<Photo>();
ArrayList<String> photo_titles = new ArrayList<String>();


private int endx = 100;
private int endy = 100;
private int width = 100;
private int height = 100;
private double jslidervalue;


    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        jcombofill();
        
    }
    private void jcombofill(){
        jcombobox.addItem("Please Select a Item");
        jcombobox.addItem("Background 1");
        jcombobox.addItem("Background 2");
        jcombobox.addItem("Bed");
        jcombobox.addItem("Chair");
        jcombobox.addItem("Chair 2");
        jcombobox.addItem("Desk");
        jcombobox.addItem("Dining Table");
        jcombobox.addItem("Dog");
        jcombobox.addItem("Lamp");
        jcombobox.addItem("Lamp 2");
        jcombobox.addItem("Plant");
        jcombobox.addItem("Plant 2");
        jcombobox.addItem("Table");
                
    }
    private void jSilderStateChanged(javax.swing.event.ChangeEvent evt){
        if(jSlider1.getValueIsAdjusting() == true){
               jSlider1.getValue();
            }
        } 

    public void redraw(java.awt.Graphics g)
    {
       for(int i = 0; i<photos.size();i++){
            photos.get(i).displayPhoto(g);      
       } 
        
           
        // to scale mutiply by a number of width and height
        // to flip horizontal/vertical make one scale integer negative
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel(){

            public void paintComponent(java.awt.Graphics g)
            {
                super.paintComponent(g);
                redraw(g);

            }

        };
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbuttonsubtract = new javax.swing.JButton();
        jbuttonx = new javax.swing.JButton();
        jbuttonadd = new javax.swing.JButton();
        jcombobox = new javax.swing.JComboBox<>();
        jSlider4 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Scale:");

        jLabel2.setText("Stretch x:");

        jLabel3.setText("Stretch y:");

        jPanel1.setBackground(new java.awt.Color(169, 169, 169));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });

        jList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jList);

        jButton1.setText("Flip Horizontal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Flip Vertical");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selected");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);

        jbuttonsubtract.setText("-");
        jbuttonsubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbuttonsubtractMousePressed(evt);
            }
        });

        jbuttonx.setBackground(new java.awt.Color(250, 250, 150));
        jbuttonx.setText("X");
        jbuttonx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbuttonxMousePressed(evt);
            }
        });

        jbuttonadd.setText("+");
        jbuttonadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbuttonaddMousePressed(evt);
            }
        });

        jcombobox.setBorder(null);
        jcombobox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbuttonsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbuttonx, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbuttonadd))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuttonx, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonadd)
                            .addComponent(jbuttonsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxActionPerformed
        // TODO add your handling code here:
        try{
        if (jcombobox.getSelectedIndex() != 0){
        Photo photo = new Photo(jcombobox.getSelectedItem().toString());             
        photos.add(photo);
        String[] photo_titles = new String[photos.size()];
        for(int i = 0; i < photos.size(); i++)
        {
            Photo p = photos.get(i);
            photo_titles[i] = p.getPhoto();
            
               
        }
        //System.out.println("Photo_titles :" + photo.getPhoto());
        jList.setListData(photo_titles);
        jList.setSelectedIndex(photos.size()-1);
        jPanel1.repaint();
        
        System.out.println(photos);
        }
        }catch(Exception e){
            System.out.println("Error wtih photo selection");
        }
    }//GEN-LAST:event_jcomboboxActionPerformed

    private void jbuttonxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonxMousePressed
        // TODO add your handling code here:
       try{ 
       if (jcombobox.getSelectedIndex() != 0){
       System.out.println("X_is_pressed");
       int index = jList.getSelectedIndex();
       System.out.println(index);
       photos.remove(index);
       String[] photo_titles = new String[photos.size()];
       for(int i = 0; i < photos.size(); i++)
       {
           Photo p = photos.get(i);
           photo_titles[i] = p.getPhoto();             
       }
       jList.setListData(photo_titles);
       jList.setSelectedIndex(photos.size()-1);
       jPanel1.repaint();
       System.out.println(photos);
       }
       }catch(Exception e){
           System.out.println("you are deleting nothing");
       }
    }//GEN-LAST:event_jbuttonxMousePressed

    private void jbuttonaddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonaddMousePressed
        // TODO add your handling code here:
        System.out.println("+_is_pressed");
        try{
            if (jcombobox.getSelectedIndex() != 0){
            int currentindex = jList.getSelectedIndex();
            int swapindex = currentindex+1;
            Photo p1 = photos.get(currentindex);
            Photo p2 = photos.get(swapindex);
            photos.set(swapindex, p1);
            photos.set(currentindex, p2);
            String[] photo_titles = new String[photos.size()];
            for(int i = 0; i < photos.size(); i++)
       {
           Photo p = photos.get(i);
           photo_titles[i] = p.getPhoto();
         
       }                       
            jList.setListData(photo_titles);
            jList.setSelectedIndex(swapindex);
            jPanel1.repaint();
            System.out.println(photos);
        }    
        }catch(Exception e){
            System.out.println("nothing is ahead");
        }
       
    
    }//GEN-LAST:event_jbuttonaddMousePressed

    private void jbuttonsubtractMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonsubtractMousePressed
        // TODO add your handling code here:
                System.out.println("-_is_pressed");
        try{
            if (jcombobox.getSelectedIndex() != 0){
            int currentindex = jList.getSelectedIndex();
            int swapindex = currentindex-1;
            Photo p1 = photos.get(currentindex);
            Photo p2 = photos.get(swapindex);
            photos.set(swapindex, p1);
            photos.set(currentindex, p2);
            String[] photo_titles = new String[photos.size()];
            for(int i = 0; i < photos.size(); i++)
       {
           Photo p = photos.get(i);
           photo_titles[i] = p.getPhoto();
         
       }
            jList.setListData(photo_titles);
            jList.setSelectedIndex(swapindex);
            jPanel1.repaint();
            System.out.println(photos);
        }    
        }catch(Exception e){
            System.out.println("nothing is behind");
        }
       
    }//GEN-LAST:event_jbuttonsubtractMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
       
       // endx = evt.getX()-(width*1/13);
       // endy = evt.getY()-(height*1/13);
        Photo p = photos.get(jList.getSelectedIndex());
        p.setImageX(evt.getX()-((int)(p.returnwidth()*0.5)));
        p.setImageY(evt.getY()-((int)(p.returnheight()*0.5)));       
        System.out.println("X = " + evt.getX() + "Y = " + evt.getY());
        jPanel1.repaint();
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        System.out.println("Vertical Button Pressed");
    }//GEN-LAST:event_jButton2MousePressed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        // TODO add your handling code here:

     
    }//GEN-LAST:event_jSlider1MouseDragged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        try{
        Photo p = photos.get(jList.getSelectedIndex());
        if(jSlider1.getValueIsAdjusting() == true){
              jslidervalue = jSlider1.getValue()/2;
              System.out.println(jslidervalue);
            }
        
        
        }catch(Exception e){
            System.out.println("Nothing is selected to scale");
        }  
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JButton jbuttonadd;
    private javax.swing.JButton jbuttonsubtract;
    private javax.swing.JButton jbuttonx;
    private javax.swing.JComboBox<String> jcombobox;
    // End of variables declaration//GEN-END:variables
}
